base_facts = [
    "CO₂ levels have increased by over 40% since the pre-industrial era.",
    "Burning coal for electricity is one of the biggest sources of CO₂ emissions.",
    "Driving a car for 1 mile produces roughly 404 grams of CO₂.",
    "Heating your home accounts for 29% of your carbon footprint.",
    "Air travel accounts for about 2.5% of global CO₂ emissions.",
    "Every ton of recycled paper saves over 1 ton of CO₂ emissions.",
    "Solar power emits 20 times less CO₂ than coal-based power plants.",
    "Switching to a plant-based diet can reduce your carbon footprint by up to 50%.",
    "Reusing a shopping bag 10 times offsets the carbon cost of producing it.",
    "Carbon footprints include both direct and indirect greenhouse gas emissions.",
    "Hydropower is a low-emission source of electricity.",
    "Methane, while not CO₂, is 25 times more potent as a greenhouse gas.",
    "A laptop uses around 200 kg of CO₂ in production and 30 kg/year in use.",
    "Bicycling to work reduces CO₂ emissions and promotes health.",
    "Carbon capture and storage is an emerging technology to reduce emissions.",
    "Composting organic waste reduces methane and CO₂ emissions.",
    "Shipping accounts for 3% of global carbon emissions.",
    "An electric kettle uses less CO₂ than boiling water on a stove.",
    "Public transport significantly lowers per-person CO₂ output.",
    "LED bulbs last longer and reduce emissions compared to CFLs.",
    "Producing 1 kg of cheese emits around 13.5 kg of CO₂ equivalents.",
    "Wind energy is among the cleanest energy sources in terms of CO₂ output.",
    "Deforestation in the Amazon significantly increases global CO₂ levels.",
    "Concrete production releases vast amounts of CO₂ into the atmosphere.",
    "Carbon footprint calculators help individuals measure and reduce their emissions.",
    "Climate change policies often target reducing national carbon footprints.",
    "Buying local food reduces transportation emissions.",
    "Air conditioners contribute significantly to household carbon footprints.",
    "Organic farming generally has a lower carbon footprint than conventional methods.",
    "Food waste contributes significantly to global CO₂ emissions.",
    "A dishwasher can be more carbon-efficient than hand washing when used correctly.",
    "The Paris Agreement aims to limit global temperature rise by reducing emissions.",
    "Carbon sinks like oceans and forests absorb a portion of emitted CO₂.",
    "E-waste recycling can reduce CO₂ emissions from electronics production.",
    "Electric scooters and bikes reduce short-distance carbon emissions.",
    "Fast fashion has a significant carbon footprint due to production and waste.",
    "High-efficiency appliances reduce household CO₂ emissions.",
    "Cement manufacturing releases CO₂ from both fuel combustion and limestone conversion.",
    "Using public libraries helps reduce digital device emissions.",
    "Rainforests are vital carbon sinks but are under threat from deforestation."
]
